# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec004d1346667a3b0dbc451d33778ca1302975ddfdb668706d7f8416ba55988b4eb3c024098cf99cacef1984cc6c21e625a31bda1bb3a8328d6c1d54832c4071

test:
  secret_key_base: a716a220ff618b0335444b4bd5cfccf2865bb035828079a68b291db1e89d3952eec0db3b328f6d1bed698f32e949da9c5a1e786659f2d5aa6f084d395a7be2c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
